apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m17b
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-m17b@sha256:91cdfe9382bc2113c886b5a8e0d586738528036be2ecd926dac37cea3e41d80c
        name: my-nodejs
        resources: {}
status: {}
